default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: db
  port: 3306

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_production
